baseURL: https://humberto.io/
DefaultContentLanguage: en
title: Humberto Rocha
theme: colordrop
pygmentsUseClasses: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
  footer:
    - identifier: github
      name: github
      url: https://github.com/humrochagf/
      weight: 1
    - identifier: twitter
      name: twitter
      url: https://twitter.com/humrochagf/
      weight: 2
    - identifier: linkedin
      name: linkedin
      url: https://linkedin.com/in/humrochagf/
      weight: 3
    - identifier: rss
      name: rss
      weight: 4
    - identifier: email
      name: email
      url: mailto:humrochagf@gmail.com
      weight: 5

params:
  description: A blog for developers and people who are interested at content about automation, frontend, backend, Python, devops, javascript game dev and much more.
  themeColor: "#000000"
  themeInverseColor: "#ffffff"
  siteLogo: /img/me.jpg
  siteLogo100: /img/me-100x100.jpg
  author:
    name: Humberto Rocha
    jobTitle: Online Programmer
    gender: male
    image: /img/me.jpg
    github: humrochagf
    twitter: humrochagf
    linkedin: humrochagf
  license:
    name: Attribuition-ShareAlike
    type: by-sa
    version: "4.0"
    locale: en
    size: 88x31

languages:
  en:
    languageName: English
    weight: 1
  pt-br:
    languageName: Português Brasileiro
    weight: 2
    params:
      description: Um blog para programadores e interessados em conteúdo sobre automação, frontend, backend, Python, devops, javascript, desenvolvimento de jogos e muito mais.
      license:
        name: Atribuição-CompartilhaIgual
        type: by-sa
        version: "4.0"
        locale: pt_BR
        size: 88x31
  fr:
    languageName: Français
    weight: 3
    params:
      description: Un blog pour les développeurs et les personnes intéressées par le contenu relatif à l’automatisation, au frontend, au backend, au Python, aux devops, au développement de jeux javascript, etc.
      license:
        name: Attribution - Partage dans les Mêmes Conditions
        type: by-sa
        version: "4.0"
        locale: fr
        size: 88x31
